[project]
name = 'Decentralized-Autonomous-Data-Marketplace-DADM'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.dataset-nft]
path = 'contracts/dataset-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.zk-computation]
path = 'contracts/zk-computation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
